const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Behaviors.Fade,
		C3.Plugins.Timeline,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Exps.cpuutilisation,
		C3.Plugins.System.Exps.gpuutilisation,
		C3.Plugins.System.Exps.objectcount,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Plugins.Eponesh_GameScore.Exps.Language,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Eponesh_GameScore.Acts.ChangeLanguage,
		C3.Plugins.TextBox.Cnds.IsFocused,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Cnds.HasTags,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Eponesh_GameScore.Cnds.OnChangeLanguage,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Cnds.DeviceType,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Eponesh_GameScore.Cnds.IsMobile,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Exps.Opacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.Mouse.Cnds.OnWheel
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{obj_player: 0},
	{obj_ground: 0},
	{obj_wallcolis: 0},
	{Keyboard: 0},
	{GamePush: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{Audio: 0},
	{scroll: 0},
	{startY: 0},
	{"9patch": 0},
	{txt_debug: 0},
	{dev_start_pos_counting: 0},
	{dictionary_tag: 0},
	{txt_debug_languagetest: 0},
	{arr_language: 0},
	{arr_playerstats: 0},
	{arr_test: 0},
	{Anchor: 0},
	{Tween: 0},
	{button_base: 0},
	{button_text: 0},
	{launchedgui_background: 0},
	{txt_launchedcounter: 0},
	{bg: 0},
	{gui_fuel_base: 0},
	{gui_fuel_value: 0},
	{gui_gameoverscreen_bg: 0},
	{gui_gameoverscreen_resultsbg: 0},
	{value: 0},
	{gui_gameoverscreen_counter: 0},
	{gui_gameoverscreen_button: 0},
	{ad_icon: 0},
	{obj_jetpack: 0},
	{gui_accelerate_base: 0},
	{gui_accelerate_text: 0},
	{jet_particles: 0},
	{wall1: 0},
	{wall2: 0},
	{wall3: 0},
	{Sine: 0},
	{Sine2: 0},
	{jet_fire: 0},
	{troll: 0},
	{grill: 0},
	{grass: 0},
	{blscr: 0},
	{plenka: 0},
	{finalbear: 0},
	{bg_sky: 0},
	{bg_forest: 0},
	{gandon_insky: 0},
	{Particles: 0},
	{player_up: 0},
	{is_fall: 0},
	{gandon_onground: 0},
	{smash: 0},
	{fuel_bonus: 0},
	{transition: 0},
	{catapult_base0: 0},
	{catapult_rezinka1: 0},
	{catapult_rezinka2: 0},
	{catapult_base1: 0},
	{catapult_base2: 0},
	{debug_setarray_key: 0},
	{debug_setarray_value: 0},
	{Fade: 0},
	{txt_catapulttip: 0},
	{txt_catapulttipshadow: 0},
	{catapult_strength: 0},
	{idea: 0},
	{spring: 0},
	{tutorial_text: 0},
	{ui_borders: 0},
	{plenka_background: 0},
	{tuto_bg: 0},
	{tuto_next: 0},
	{tuto_previous: 0},
	{tutoimages: 0},
	{tutoplenka: 0},
	{TiledBackground: 0},
	{txt_victory: 0},
	{TimelineController: 0},
	{firecracker_particles: 0},
	{firecracker: 0},
	{shop_items: 0},
	{shop_title: 0},
	{shoptitlebg: 0},
	{shop_title_anchor: 0},
	{txt_localizate: 0},
	{debug: 0},
	{length: 0},
	{height: 0},
	{fuel: 0},
	{plusbalance: 0},
	{gameover: 0},
	{viewgui: 0},
	{launched: 0},
	{gandons_smashed: 0},
	{jet_strength: 0},
	{jet_maxspeed: 0},
	{jet_fueleat: 0},
	{tag: 0},
	{x: 0},
	{y: 0},
	{shake: 0},
	{zoom: 0},
	{lerp_speed: 0},
	{factor: 0},
	{thislaunch_maxheight: 0},
	{intransition: 0},
	{transition_time: 0},
	{buttonscan: 0},
	{angleef: 0},
	{scrollPos: 0},
	{scrollTouchY: 0},
	{scrollMax: 0},
	{scrollSpeed: 0},
	{overEdgeResponce: 0},
	{sensibility: 0}
];

self.InstanceType = {
	obj_player: class extends self.ISpriteInstance {},
	obj_ground: class extends self.ITiledBackgroundInstance {},
	obj_wallcolis: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	scroll: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	txt_debug: class extends self.ITextInstance {},
	dev_start_pos_counting: class extends self.ISpriteInstance {},
	txt_debug_languagetest: class extends self.ITextInstance {},
	arr_language: class extends self.IDictionaryInstance {},
	arr_playerstats: class extends self.IDictionaryInstance {},
	arr_test: class extends self.IArrayInstance {},
	button_base: class extends self.ISpriteInstance {},
	button_text: class extends self.ITextInstance {},
	launchedgui_background: class extends self.ISpriteInstance {},
	txt_launchedcounter: class extends self.ITextInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	gui_fuel_base: class extends self.ISpriteInstance {},
	gui_fuel_value: class extends self.ITiledBackgroundInstance {},
	gui_gameoverscreen_bg: class extends self.ITiledBackgroundInstance {},
	gui_gameoverscreen_resultsbg: class extends self.ISpriteInstance {},
	gui_gameoverscreen_counter: class extends self.ITextInstance {},
	gui_gameoverscreen_button: class extends self.ITextInstance {},
	ad_icon: class extends self.ISpriteInstance {},
	obj_jetpack: class extends self.ISpriteInstance {},
	gui_accelerate_base: class extends self.ISpriteInstance {},
	gui_accelerate_text: class extends self.ITextInstance {},
	jet_particles: class extends self.IParticlesInstance {},
	wall1: class extends self.ITiledBackgroundInstance {},
	wall2: class extends self.ITiledBackgroundInstance {},
	wall3: class extends self.ITiledBackgroundInstance {},
	jet_fire: class extends self.ISpriteInstance {},
	troll: class extends self.ISpriteInstance {},
	grill: class extends self.ISpriteInstance {},
	grass: class extends self.ITiledBackgroundInstance {},
	blscr: class extends self.ITiledBackgroundInstance {},
	plenka: class extends self.ISpriteInstance {},
	finalbear: class extends self.ISpriteInstance {},
	bg_sky: class extends self.ISpriteInstance {},
	bg_forest: class extends self.ITiledBackgroundInstance {},
	gandon_insky: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	player_up: class extends self.ISpriteInstance {},
	gandon_onground: class extends self.ISpriteInstance {},
	smash: class extends self.ISpriteInstance {},
	fuel_bonus: class extends self.ISpriteInstance {},
	transition: class extends self.ITiledBackgroundInstance {},
	catapult_base0: class extends self.ISpriteInstance {},
	catapult_rezinka1: class extends self.ISpriteInstance {},
	catapult_rezinka2: class extends self.ISpriteInstance {},
	catapult_base1: class extends self.ISpriteInstance {},
	catapult_base2: class extends self.ISpriteInstance {},
	debug_setarray_key: class extends self.ITextInputInstance {},
	debug_setarray_value: class extends self.ITextInputInstance {},
	txt_catapulttip: class extends self.ITextInstance {},
	txt_catapulttipshadow: class extends self.ITextInstance {},
	catapult_strength: class extends self.ISpriteInstance {},
	idea: class extends self.ISpriteInstance {},
	spring: class extends self.ISpriteInstance {},
	tutorial_text: class extends self.ITextInstance {},
	ui_borders: class extends self.ITiledBackgroundInstance {},
	plenka_background: class extends self.ITiledBackgroundInstance {},
	tuto_bg: class extends self.ITiledBackgroundInstance {},
	tuto_next: class extends self.ISpriteInstance {},
	tuto_previous: class extends self.ISpriteInstance {},
	tutoimages: class extends self.ISpriteInstance {},
	tutoplenka: class extends self.IWorldInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	txt_victory: class extends self.ITextInstance {},
	TimelineController: class extends self.IInstance {},
	firecracker_particles: class extends self.IParticlesInstance {},
	firecracker: class extends self.ISpriteInstance {},
	shop_items: class extends self.ISpriteInstance {},
	shop_title: class extends self.ITextInstance {},
	shoptitlebg: class extends self.ISpriteInstance {},
	shop_title_anchor: class extends self.ITextInstance {},
	txt_localizate: class extends self.ITextInstance {}
}